import type { Project, Shot } from "./types";

const characters: Project["characters"] = [
  {
    id: "c-shenzhao",
    name: "沈昭",
    age: "二十四 / 四十七",
    role: "归墟剑宗大弟子，后为魔尊",
    personality: "寡言、执拗、重诺。对师门有近乎偏执的忠诚，直到被师门放弃。",
    catchphrase: "「我从不说第二遍。」",
    relations: "云岫的同门师兄；玄真子的亲传弟子。",
    personas: [
      {
        id: "p-shenzhao-young",
        tag: "青年",
        description: "束发，玄色宗门道袍，腰悬断纹长剑「未央」。眉眼清冷，左颊一道浅疤。",
        prompt: "水墨工笔风。人物设定图：沈昭，束发，玄色道袍，腰悬断纹长剑，眉眼清冷，左颊浅疤。展示整体造型，含正面、侧面与背面，全身，干净背景。",
        sheetReady: true,
      },
      {
        id: "p-shenzhao-demon",
        tag: "入魔",
        description: "披发，衣袍染成暗赤，瞳色转金，左颊疤痕裂开延至颈侧。剑身生出黑纹。",
        prompt: "水墨工笔风。人物设定图：沈昭入魔形态，披发，暗赤衣袍，金瞳，颊疤延至颈侧，剑身黑纹。展示整体造型，含正面、侧面与背面，全身，干净背景。",
        sheetReady: true,
      },
      {
        id: "p-shenzhao-old",
        tag: "老年",
        description: "鬓发斑白，粗布衣，背微驼，剑已断，只余剑柄。",
        prompt: "",
        sheetReady: false,
      },
    ],
    voice: { source: "minimax_system", label: "MiniMax · 青年男声 · 沉稳", sampleReady: true },
  },
  {
    id: "c-yunxiu",
    name: "云岫",
    age: "十九",
    role: "归墟剑宗小师妹",
    personality: "明亮、直率、心软。是宗门里唯一肯替沈昭说话的人。",
    catchphrase: "「师兄，你回头看看我。」",
    relations: "沈昭的师妹；玄真子的关门弟子。",
    personas: [
      {
        id: "p-yunxiu-girl",
        tag: "少女",
        description: "双环髻，月白道袍，袖口绣青竹。手腕系一条红绳。",
        prompt: "水墨工笔风。人物设定图：云岫，双环髻，月白道袍，袖口青竹纹，腕系红绳。展示整体造型，含正面、侧面与背面，全身，干净背景。",
        sheetReady: true,
      },
      {
        id: "p-yunxiu-snow",
        tag: "雪夜",
        description: "披白狐裘，发髻散乱，红绳断了一截。",
        prompt: "",
        sheetReady: false,
      },
    ],
    voice: { source: "upload", label: "上传 · yunxiu_ref_01.wav · 00:14", sampleReady: true },
  },
  {
    id: "c-xuanzhen",
    name: "玄真子",
    age: "七十余",
    role: "归墟剑宗掌门",
    personality: "温和外表下极度理性，为宗门可以牺牲任何人。",
    catchphrase: "「宗门在，人才在。」",
    relations: "沈昭与云岫的师父。",
    personas: [
      {
        id: "p-xuanzhen-old",
        tag: "老年",
        description: "白须及胸，鹤氅，持竹杖。目光平静。",
        prompt: "水墨工笔风。人物设定图：玄真子，白须及胸，鹤氅，竹杖。展示整体造型，含正面、侧面与背面，全身，干净背景。",
        sheetReady: true,
      },
    ],
    voice: { source: "minimax_system", label: "MiniMax · 老年男声 · 温厚", sampleReady: false },
  },
];

const sourceText = [
  "雪从午后就没停过。断桥上的积雪没到脚踝，沈昭站在桥心，剑还在鞘里。",
  "「师兄。」云岫从桥那头跑来，狐裘上落满了雪，「师父说，只要你交出未央剑，一切都可以不算。」",
  "沈昭没有回头。他望着桥下结了冰的河，说：「他说的是剑，不是我。」",
  "云岫停在三步外。她想再往前，脚下的雪却像被什么钉住了。",
  "「你回头看看我。」她说。",
  "沈昭终于转身。他的眼睛已经是金色的，左颊的疤裂到了颈侧，像一道还没干的墨。",
  "桥那头传来竹杖点地的声音。玄真子来了，身后是整座宗门的灯。",
  "「昭儿。」老人的声音很轻，「宗门在，人才在。」",
  "沈昭拔剑。剑身上的黑纹亮了一瞬。雪，忽然停了。",
];

const units: Project["chapters"][number]["units"] = [
  { id: "u1", index: 1, summary: "断桥雪，沈昭独立桥心", sourceRange: [0, 0] },
  { id: "u2", index: 2, summary: "云岫赶来传话", sourceRange: [1, 2] },
  { id: "u3", index: 3, summary: "三步之隔，「你回头看看我」", sourceRange: [3, 5] },
  { id: "u4", index: 4, summary: "玄真子携宗门灯火而至", sourceRange: [6, 7] },
  { id: "u5", index: 5, summary: "拔剑，雪停", sourceRange: [8, 8] },
];

const COSTS = [0.82, 0.71, 1.12, 0.95, 0.64, 0.58, 0.77, 0.9, 0, 0, 0, 0, 0];

let n = 0;
function shot(partial: Omit<Shot, "id" | "index" | "cost">): Shot {
  n += 1;
  return { id: `s-${n}`, index: n, cost: COSTS[n - 1] ?? 0, ...partial };
}

const shots: Shot[] = [
  shot({
    unitId: "u1",
    scene: "断桥 · 黄昏 · 大雪",
    shotSize: "大远景",
    camera: "固定，微微下摇，雪片前景飘落",
    duration: 5,
    characters: [{ characterId: "c-shenzhao", personaTag: "入魔" }],
    dialogue: [],
    emotion: "孤绝，天地间只剩一人",
    action: "沈昭独立桥心，背影，剑在鞘中",
    sound: "风雪声，远处隐约的钟声",
    framePrompt: "",
    videoPrompt: "水墨工笔风格，黄昏大雪中的古石桥大远景，一名披发暗赤衣袍的男子背对镜头独立桥心，剑在鞘中，雪片从前景飘落，镜头缓慢下摇，风雪声与远处钟声。",
    frameMode: "text_only",
    status: "done",
  }),
  shot({
    unitId: "u1",
    scene: "断桥 · 黄昏 · 大雪",
    shotSize: "近景",
    camera: "固定，浅景深",
    duration: 4,
    characters: [{ characterId: "c-shenzhao", personaTag: "入魔" }],
    dialogue: [],
    emotion: "压抑，等待",
    action: "积雪没过脚踝，剑柄上落雪，手指微微收紧",
    sound: "雪落声，衣料摩擦",
    framePrompt: "水墨工笔风。近景，浅景深，一只手握在断纹长剑的剑柄上，剑柄落着雪，暗赤色袖口，背景是虚化的雪中石桥。竖屏 9:16 构图。无文字无水印。",
    videoPrompt: "近景固定镜头，握剑的手指缓缓收紧，雪落在剑柄上，衣料轻微摩擦声。",
    frameMode: "image",
    status: "done",
  }),
  shot({
    unitId: "u2",
    scene: "断桥桥头 · 黄昏 · 大雪",
    shotSize: "全景",
    camera: "跟拍，手持感，由后向前",
    duration: 6,
    characters: [{ characterId: "c-yunxiu", personaTag: "雪夜" }],
    dialogue: [{ characterId: "c-yunxiu", line: "师兄。", tone: "急切，喘息" }],
    emotion: "急切",
    action: "云岫披狐裘从桥头跑来，狐裘上落满雪",
    sound: "急促脚步踏雪，喘息",
    framePrompt: "水墨工笔风。全景，一名披白狐裘的少女在雪中石桥上奔跑，发髻散乱，狐裘上落满雪，黄昏光线。竖屏 9:16 构图。无文字无水印。",
    videoPrompt: "手持跟拍全景，少女披白狐裘在大雪中沿石桥奔跑，喊出「师兄」，急促脚步踏雪声与喘息。保持人物外貌与参考图一致。",
    frameMode: "image",
    status: "video_ready",
    needsReview: true,
  }),
  shot({
    unitId: "u2",
    scene: "断桥 · 黄昏 · 大雪",
    shotSize: "中景",
    camera: "固定",
    duration: 7,
    characters: [{ characterId: "c-yunxiu", personaTag: "雪夜" }],
    dialogue: [{ characterId: "c-yunxiu", line: "师父说，只要你交出未央剑，一切都可以不算。", tone: "急切中带哀求" }],
    emotion: "哀求",
    action: "云岫停下，胸口起伏，望向沈昭背影",
    sound: "风声渐弱",
    framePrompt: "水墨工笔风。中景，披白狐裘的少女停在雪中石桥上，胸口起伏，望向画面深处，发髻散乱，腕上红绳断了一截。竖屏 9:16 构图。无文字无水印。",
    videoPrompt: "中景固定，少女停下喘息，说出「师父说，只要你交出未央剑，一切都可以不算」，语气急切带哀求，风声渐弱。",
    frameMode: "image",
    status: "video_generating",
  }),
  shot({
    unitId: "u2",
    scene: "断桥 · 黄昏 · 大雪",
    shotSize: "近景",
    camera: "固定，人物侧面",
    duration: 6,
    characters: [{ characterId: "c-shenzhao", personaTag: "入魔" }],
    dialogue: [{ characterId: "c-shenzhao", line: "他说的是剑，不是我。", tone: "平静，冷" }],
    emotion: "平静下的决绝",
    action: "沈昭不回头，目光落在桥下结冰的河面",
    sound: "冰面细微开裂声",
    framePrompt: "水墨工笔风。近景侧面，披发男子的侧脸，金色瞳孔，左颊疤痕延至颈侧，目光下垂望向桥下，暗赤衣领，雪片飘落。竖屏 9:16 构图。无文字无水印。",
    videoPrompt: "近景侧面固定，男子不回头，目光落向桥下冰面，低声说「他说的是剑，不是我」，语气平静而冷，伴有冰面细微开裂声。",
    frameMode: "image",
    status: "frame_approved",
  }),
  shot({
    unitId: "u3",
    scene: "断桥 · 黄昏 · 大雪",
    shotSize: "特写",
    camera: "固定，俯拍",
    duration: 4,
    characters: [{ characterId: "c-yunxiu", personaTag: "雪夜" }],
    dialogue: [],
    emotion: "迟疑，被钉住",
    action: "云岫的鞋停在雪里，想往前，却动不了",
    sound: "雪被压实的声音",
    framePrompt: "水墨工笔风。俯拍特写，一双绣鞋陷在积雪中，鞋尖前方三步是另一个人的衣摆，雪片落下。竖屏 9:16 构图。无文字无水印。",
    videoPrompt: "俯拍特写，绣鞋在雪中微微前移又停住，雪被压实的声音。",
    frameMode: "image",
    status: "frame_ready",
  }),
  shot({
    unitId: "u3",
    scene: "断桥 · 黄昏 · 大雪",
    shotSize: "近景",
    camera: "缓慢推近",
    duration: 5,
    characters: [{ characterId: "c-yunxiu", personaTag: "雪夜" }],
    dialogue: [{ characterId: "c-yunxiu", line: "你回头看看我。", tone: "轻，颤抖" }],
    emotion: "脆弱",
    action: "云岫抬头，眼里有雪也有泪",
    sound: "极静，只有雪",
    framePrompt: "水墨工笔风。近景，披白狐裘的少女抬头，眼里含泪，雪片落在睫毛上，黄昏侧光。竖屏 9:16 构图。无文字无水印。",
    videoPrompt: "缓慢推近近景，少女抬头，眼含泪光，轻声说「你回头看看我」，声音颤抖，环境极静。",
    frameMode: "image",
    status: "frame_generating",
  }),
  shot({
    unitId: "u3",
    scene: "断桥 · 黄昏 · 大雪",
    shotSize: "中景",
    camera: "固定，人物转身入画",
    duration: 6,
    characters: [{ characterId: "c-shenzhao", personaTag: "入魔" }],
    dialogue: [],
    emotion: "揭示，压迫",
    action: "沈昭转身，金瞳，颊疤裂至颈侧",
    sound: "风忽然停了一瞬",
    framePrompt: "水墨工笔风。中景，披发男子正在转身，半张脸入画，金色瞳孔，左颊疤痕如未干墨迹延至颈侧，暗赤衣袍，雪中石桥。竖屏 9:16 构图。无文字无水印。",
    videoPrompt: "中景固定，男子缓缓转身面向镜头，金瞳显露，颊疤延至颈侧，风声骤停。保持人物外貌与参考图一致。",
    frameMode: "image",
    status: "storyboard_approved",
  }),
  shot({
    unitId: "u3",
    scene: "断桥 · 黄昏 · 大雪",
    shotSize: "大特写",
    camera: "固定",
    duration: 4,
    characters: [{ characterId: "c-shenzhao", personaTag: "入魔" }],
    dialogue: [],
    emotion: "非人",
    action: "金色瞳孔，瞳孔中倒映着云岫",
    sound: "心跳",
    framePrompt: "水墨工笔风。大特写，一只金色的眼睛，瞳孔中倒映着雪中披狐裘的少女，眼角有裂开的疤。竖屏 9:16 构图。无文字无水印。",
    videoPrompt: "大特写固定，金色瞳孔微微收缩，瞳中倒影的少女轻轻晃动，心跳声。",
    frameMode: "image",
    status: "draft",
    needsReview: true,
  }),
  shot({
    unitId: "u4",
    scene: "断桥桥头 · 入夜 · 雪",
    shotSize: "远景",
    camera: "固定，灯火由远及近",
    duration: 8,
    characters: [{ characterId: "c-xuanzhen", personaTag: "老年" }],
    dialogue: [],
    emotion: "压迫，宿命感",
    action: "玄真子持竹杖走来，身后整座宗门的灯火",
    sound: "竹杖点地，脚步众多",
    framePrompt: "",
    videoPrompt: "水墨工笔风格，入夜雪中石桥远景，一名白须鹤氅老者持竹杖缓步走来，身后是数十盏灯火沿山道蜿蜒而下，竹杖点地声与众多脚步声。",
    frameMode: "text_only",
    status: "draft",
  }),
  shot({
    unitId: "u4",
    scene: "断桥桥头 · 入夜 · 雪",
    shotSize: "近景",
    camera: "固定，仰角",
    duration: 6,
    characters: [{ characterId: "c-xuanzhen", personaTag: "老年" }],
    dialogue: [{ characterId: "c-xuanzhen", line: "昭儿。宗门在，人才在。", tone: "很轻，温和，不容置疑" }],
    emotion: "温和的残忍",
    action: "玄真子停步，目光平静",
    sound: "灯火摇曳",
    framePrompt: "水墨工笔风。仰角近景，白须及胸的老者，鹤氅，持竹杖，目光平静，身后灯火虚化。竖屏 9:16 构图。无文字无水印。",
    videoPrompt: "仰角近景固定，老者停步，轻声说「昭儿。宗门在，人才在」，语气温和却不容置疑，灯火摇曳声。",
    frameMode: "image",
    status: "draft",
  }),
  shot({
    unitId: "u5",
    scene: "断桥 · 入夜 · 雪停",
    shotSize: "中景",
    camera: "快速推近，随拔剑动作",
    duration: 5,
    characters: [{ characterId: "c-shenzhao", personaTag: "入魔" }],
    dialogue: [],
    emotion: "决裂",
    action: "沈昭拔剑，剑身黑纹亮起一瞬",
    sound: "出鞘声，低沉嗡鸣",
    framePrompt: "水墨工笔风。中景，披发男子正在拔剑，剑身带黑色纹路并泛出微光，暗赤衣袍翻飞，雪中石桥。竖屏 9:16 构图。无文字无水印。",
    videoPrompt: "中景快速推近，男子拔剑出鞘，剑身黑纹亮起一瞬，出鞘声与低沉嗡鸣。",
    frameMode: "image",
    status: "draft",
  }),
  shot({
    unitId: "u5",
    scene: "断桥 · 入夜 · 雪停",
    shotSize: "大远景",
    camera: "固定，长镜",
    duration: 8,
    characters: [
      { characterId: "c-shenzhao", personaTag: "入魔" },
      { characterId: "c-yunxiu", personaTag: "雪夜" },
      { characterId: "c-xuanzhen", personaTag: "老年" },
    ],
    dialogue: [],
    emotion: "静止，一切将发生",
    action: "雪忽然停了，三人在桥上成一线",
    sound: "绝对安静",
    framePrompt: "",
    videoPrompt: "水墨工笔风格，入夜石桥大远景，三人在桥上成一条直线：桥心持剑的披发男子、三步外披狐裘的少女、桥头持竹杖的老者与身后灯火。空中飘落的雪片逐渐减少直至完全停止，画面归于绝对安静。",
    frameMode: "text_only",
    status: "draft",
  }),
];

export const projects: Project[] = [
  {
    id: "p-guixu",
    title: "归墟",
    genre: ["仙侠", "虐恋", "入魔"],
    orientation: "9:16",
    targetEpisodes: 24,
    world:
      "灵气衰竭的末法之世。修行者以剑为器，剑有裂纹者可通「归墟」，即万物终结之处。宗门以血脉与剑谱维系，弟子一旦入魔即被逐出，剑归宗门。\n\n禁忌：不可直呼归墟之名；不可让断剑落入河中。",
    style:
      "水墨工笔。线条细而肯定，设色以墨、赭、月白为主，偶用朱砂点睛。光线偏冷，雪景为主调。人物比例写实，不做夸张。镜头语言偏静，多固定机位与缓慢推拉。",
    styleRefs: 3,
    characters,
    chapters: [
      {
        id: "ch-1",
        index: 1,
        title: "断桥雪",
        sourceText,
        units,
        shots,
        updatedAt: "2026-09-06 09:41",
      },
      {
        id: "ch-2",
        index: 2,
        title: "剑归宗",
        sourceText: [],
        units: [],
        shots: [],
        updatedAt: "2026-09-05 22:10",
      },
    ],
    updatedAt: "2026-09-06 09:41",
  },
  {
    id: "p-jiuzhong",
    title: "九重雪",
    genre: ["古装", "权谋"],
    orientation: "9:16",
    targetEpisodes: 12,
    world: "",
    style: "",
    styleRefs: 0,
    characters: [],
    chapters: [],
    updatedAt: "2026-09-02 18:03",
  },
  {
    id: "p-huoshan",
    title: "火山下的便利店",
    genre: ["现代", "轻喜剧"],
    orientation: "9:16",
    targetEpisodes: 30,
    world: "",
    style: "",
    styleRefs: 1,
    characters: [],
    chapters: [],
    updatedAt: "2026-08-28 11:20",
  },
];

export function getProject(id: string) {
  return projects.find((p) => p.id === id) ?? null;
}

export function getChapter(projectId: string, chapterId: string) {
  const p = getProject(projectId);
  return p?.chapters.find((c) => c.id === chapterId) ?? null;
}

export function characterById(project: Project, id: string) {
  return project.characters.find((c) => c.id === id) ?? null;
}
